name: Improvement
description: Suggest an improvement to existing items or workflow
labels: ['improvement']
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to change?
    validations:
      required: true
  - type: input
    id: area
    attributes:
      label: Area
      description: e.g. tooling, docs
    validations:
      required: false
